# Using default values from dev compose
[databases.mongo]
connection_uri = "mongodb://{username}:{password}@mongo:27017/?authSource=admin"
username = "subtask"
password = "subtask"
database = "subtask"

# Using default values from dev compose
[databases.redis]
connection_uri = "redis://{username}:{password}@redis:6379/{database}"
username = "default"
password = "subtask"
database = "0"

[oauth.github]
app_id = "<APP ID>"
client_id = "<CLIENT ID>"
client_secret = "<CLIENT SECRET>"
private_key = """-----BEGIN RSA PRIVATE KEY-----
<LONG RSA PRIVATE KEY>
-----END RSA PRIVATE KEY-----"""
